server:
  amqp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    heartbeat: 15
    exchange: eeagent

eeagent:
    name: eeagent
    heartbeat: 30
    poll_interval: 2

    launch_types:
#        pyon:
#            directory: /tmp
        supd:
            directory: /tmp/SupD
            slots: 8

pd:
    name: PDHost1

loggers:
  eeagent:
    handlers: [console]
    level: INFO

