server:
  amqp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    heartbeat: 10

dashi:
    exchange: eeagentEX

eeagent:
    name: eeagent
    heartbeat: 30
    poll_interval: 2

    launch_type:
#       name: pyon_single
#       working_directory: needs to be filled in
#       container_args: --noshell
#       supd_directory: /tmp/SupD
    slots: 8

pd:
    name: PDHost1

loggers:
  eeagent:
    handlers: [console]
    level: INFO

